const defaultPrompts = [
  { id: '01', title: '系统 Prompt', text: '你是一位资深的飞书商业化售前顾问，拥有5年企业数字化转型咨询经验。所有分析必须基于客户实际业务场景，具体到飞书产品功能模块，并量化时间、成本与效率价值。语气专业、结构化、有咨询感。' },
  { id: '02', title: '行业调研 Agent', text: '针对 {industry} 行业，输出3条有场景与数据支撑的数字化趋势、Top 5 业务痛点、2个标杆案例及政策/合规要求。痛点必须对应具体岗位或业务流程，禁止泛泛而谈。' },
  { id: '03', title: '痛点诊断 Agent', text: '基于客户行业、规模、自述痛点与行业调研，输出表面问题→根因映射、影响程度×紧迫性优先级、6个月风险和解决方向预判。' },
  { id: '04', title: '方案匹配 Agent', text: '基于诊断结果设计飞书产品组合，说明典型业务流程、方案架构、功能模块、AI 增强点与三期实施路径，具体到产品与使用角色。' },
  { id: '05', title: '文档生成 Agent', text: '将调研、诊断和方案整合为3-4页 A4 提案：客户现状、行业洞察、解决方案、量化 ROI、实施保障、下一步行动。每段不超过3行，关键数字加粗。' }
];
const products = [
  ['多维表格', '轻量业务系统搭建，自动化流程与数据看板', '▦'], ['审批', '条件分支、多级审批、移动端请假调班', '✓'], ['项目', 'OKR、甘特图、里程碑与资源分配', '◫'], ['知识库', '权限管理、全文检索与版本控制', '⌂'], ['妙记', '录音转文字，自动提取待办与会议纪要', '◌'], ['智能伙伴', '问答、内容生成与数据分析', '✦'], ['群机器人', '接入业务系统，自动推送关键消息', '♢'], ['日历', '智能日程、会议室预订与忙闲视图', '◷'], ['文档', '实时协同编辑、评论与多维表格嵌入', '▤']
];
let memories = JSON.parse(localStorage.getItem('feishu_memories') || '[]');
let promptState = JSON.parse(localStorage.getItem('feishu_prompts') || 'null') || defaultPrompts;
let currentProposal = null;
let timer;

const $ = (id) => document.getElementById(id);
const toast = (msg) => { const el = $('toast'); el.textContent = msg; el.classList.add('show'); clearTimeout(el._t); el._t = setTimeout(() => el.classList.remove('show'), 2200); };
const formatDate = (d = new Date()) => new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(d);
function updateMemoryUI(){ $('historyCount').textContent = memories.length; $('memoryLabel').textContent = `记忆 ${memories.length} 条`; }

function renderProposal(data){
  const root = $('proposalResult');
  root.innerHTML = `<div class="proposal-toolbar"><span class="proposal-status">● 已完成 · 生成于 ${formatDate()}</span><div class="proposal-actions"><button class="tool-btn" id="copyBtn">□ 复制 Markdown</button><button class="tool-btn" id="downloadBtn">↓ 导出 .md</button><button class="tool-btn" id="feishuDocBtn">▤ 写入飞书文档</button></div></div><div class="proposal-body"><div class="proposal-kicker">FEISHU AI SOLUTION / 2026</div><h2>${data.clientName} · 飞书 AI 数字化转型方案</h2><div class="proposal-meta">${data.industry}  ·  ${data.scale}  ·  售前初版</div><div class="proposal-tabs"><button class="proposal-tab active" data-tab="diagnosis">01 痛点诊断</button><button class="proposal-tab" data-tab="solution">02 解决方案</button><button class="proposal-tab" data-tab="value">03 预期价值</button></div><div id="proposalPanel"></div><div class="iteration-box"><label>让方案更贴近客户 · 输入反馈即可迭代</label><div class="iteration-row"><input id="feedbackInput" placeholder="例如：补充区域经理的管理视角" /><button id="iterateBtn">迭代方案 →</button></div></div></div>`;
  $('copyBtn').onclick = () => { navigator.clipboard?.writeText(toMarkdown(data)); toast('Markdown 已复制'); };
  $('downloadBtn').onclick = () => downloadMarkdown(data);
  $('feishuDocBtn').onclick = () => { toast('已生成飞书文档草稿 · 接入 API 后可自动写入'); };
  root.querySelectorAll('.proposal-tab').forEach(btn => btn.onclick = () => { root.querySelectorAll('.proposal-tab').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); renderPanel(btn.dataset.tab, data); });
  $('iterateBtn').onclick = () => { const v = $('feedbackInput').value.trim(); if(!v) return toast('请先写下你的修改意见'); data.feedback = v; data.version = (data.version || 1) + 1; saveMemory(data); renderPanel('solution', data); $('feedbackInput').value=''; toast('已根据反馈更新方案'); };
  renderPanel('diagnosis', data);
}
function renderPanel(tab, data){
  const panel = $('proposalPanel');
  if(tab === 'diagnosis') panel.innerHTML = `<div class="proposal-section-title">表面问题 → 根因映射</div><table class="diagnosis-table"><thead><tr><th>客户描述</th><th>根因分析</th><th>影响范围</th></tr></thead><tbody><tr><td>排班依赖 Excel，版本混乱</td><td>排班数据没有统一入口，更新靠人工转发</td><td><span class="pill high">高影响</span></td></tr><tr><td>请假调班漏通知</td><td>审批与排班断开，变更没有触达相关角色</td><td><span class="pill high">高紧迫</span></td></tr><tr><td>总部无法实时掌握人力</td><td>门店数据未沉淀为可视化指标</td><td><span class="pill mid">中影响</span></td></tr></tbody></table><div class="proposal-section-title">6 个月风险预判</div><p class="proposal-lead">若继续依赖人工同步，排班错误率可能升至 <strong>15%</strong>，月度人力成本超支约 <strong>8%</strong>；总部每周需投入约 <strong>24 小时</strong>核对门店数据。</p><div class="proposal-section-title">诊断结论</div><p class="proposal-lead">这不是“排班表做得不够好”，而是需要建立一套<strong>信息实时同步 + 流程自动化</strong>的门店协同机制。</p>`;
  if(tab === 'solution') panel.innerHTML = `<div class="proposal-section-title">核心产品组合</div><div class="product-stack"><div class="product-card"><b>多维表格</b><span>统一排班底表 · 门店数据看板</span></div><div class="product-card"><b>审批</b><span>请假调班 · 条件分支</span></div><div class="product-card"><b>群机器人</b><span>变更通知 · 触达责任人</span></div></div><div class="proposal-section-title">典型业务流程</div><div class="arch-flow"><span class="arch-node">店长提交排班</span><i class="arch-arrow">→</i><span class="arch-node">多维表格校验</span><i class="arch-arrow">→</i><span class="arch-node">审批自动流转</span><i class="arch-arrow">→</i><span class="arch-node">机器人通知</span></div><p class="proposal-lead">AI 增强：智能伙伴按门店客流预测生成排班建议；多维表格 AI 字段自动识别缺岗与冲突，异常实时推送总部。</p><div class="proposal-section-title">三期实施路径</div><p class="proposal-lead"><strong>一期 1-2 周</strong>：上线排班底表与请假审批，覆盖 5 家试点门店。<br /><strong>二期 1 个月</strong>：推广至全部门店，接入群机器人。<br /><strong>三期 3 个月</strong>：接入经营数据，建立人效分析看板。</p>`;
  if(tab === 'value') panel.innerHTML = `<div class="proposal-section-title">量化价值预估</div><div class="value-highlight"><div class="metric"><strong>24h</strong><span>总部每周核对时间减少</span></div><div class="metric"><strong>↓ 60%</strong><span>排班沟通耗时</span></div><div class="metric"><strong>8%</strong><span>人力成本可控空间</span></div></div><table class="value-table"><thead><tr><th>指标</th><th>当前状态</th><th>预期改善</th><th>量化价值</th></tr></thead><tbody><tr><td>排班同步</td><td>人工转发，平均 T+1</td><td>实时同步</td><td>每月节省 96 小时</td></tr><tr><td>调班通知</td><td>漏通知约 10%</td><td>自动触达 100%</td><td>减少 30% 临时加班</td></tr><tr><td>总部巡检</td><td>每周手工汇总</td><td>看板实时可见</td><td>月度少 1 人天</td></tr></tbody></table><div class="proposal-section-title">方案收益</div><p class="proposal-lead">按 50 家门店测算，预计首年直接节省管理与沟通成本约 <strong>¥28.8 万</strong>，并为后续智能排班与精细化人效管理打下数据基础。</p>`;
}
function toMarkdown(d){ return `# ${d.clientName} 飞书 AI 数字化转型方案\n\n## 一、客户现状与痛点\n- 行业：${d.industry}\n- 规模：${d.scale}\n- 痛点：${d.painPoints}\n\n## 二、行业洞察\n- 连锁门店需要统一排班入口与实时协同。\n- 移动审批与自动通知正在成为门店运营标配。\n\n## 三、解决方案设计\n多维表格 + 审批 + 群机器人，串联排班、调班、通知全流程；智能伙伴生成排班建议。\n\n## 四、预期价值与 ROI\n|指标|当前状态|预期改善|量化价值|\n|---|---|---|---|\n|排班同步|人工 T+1|实时同步|每月节省 96 小时|\n|调班通知|漏通知约 10%|自动触达 100%|减少 30% 临时加班|\n\n## 五、实施保障\n- 一期 1-2 周试点，二期 1 个月覆盖全门店，三期 3 个月完成数据智能化。\n\n## 六、下一步行动\n本周完成需求确认会，下周输出详细蓝图。`; }
function downloadMarkdown(d){ const blob = new Blob([toMarkdown(d)],{type:'text/markdown;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${d.clientName}-飞书AI方案.md`; a.click(); URL.revokeObjectURL(a.href); toast('方案已导出'); }
function saveMemory(data){ const i=memories.findIndex(x=>x.clientName===data.clientName); if(i>=0) memories[i]=data; else memories.unshift(data); memories=memories.slice(0,20); localStorage.setItem('feishu_memories',JSON.stringify(memories)); updateMemoryUI(); }
function runGeneration(data){ $('resultEmpty').classList.add('hidden'); $('proposalResult').classList.add('hidden'); $('resultLoading').classList.remove('hidden'); let step=0; const steps=[['research','正在检索行业趋势与案例',24],['diagnosis','正在拆解业务根因',46],['matching','正在组合飞书产品能力',72],['document','正在整理 3 页提案文档',100]]; clearInterval(timer); timer=setInterval(()=>{ if(step>=steps.length){ clearInterval(timer); setTimeout(()=>{ $('resultLoading').classList.add('hidden'); $('proposalResult').classList.remove('hidden'); currentProposal=data; saveMemory(data); renderProposal(data); $('crumbTitle').textContent=data.clientName; toast('方案已生成，可继续迭代'); },450); return; } const [key,title,pct]=steps[step]; $('loadingTitle').textContent=title; $('progressBar').style.width=pct+'%'; document.querySelectorAll('.load-step').forEach(el=>{const active=el.dataset.step===key; const done=steps.findIndex(s=>s[0]===el.dataset.step)<step; el.classList.toggle('active',active); el.querySelector('i').textContent=done?'已完成':active?'进行中':'等待中';}); step++; },850); }

function renderHistory(){ const el=$('historyList'); if(!memories.length){el.innerHTML='<div class="result-empty" style="min-height:300px"><h3>还没有提案记忆</h3><p>生成第一份方案后，客户上下文会自动保存在这里。</p></div>';return;} el.innerHTML=memories.map((m,i)=>`<div class="history-card"><div><h3>${m.clientName} · ${m.industry}</h3><p>${m.scale}　${m.painPoints.slice(0,65)}${m.painPoints.length>65?'…':''}</p></div><div><span class="history-date">${m.savedAt || '刚刚保存'}</span><button class="tool-btn open-memory" data-index="${i}">打开</button></div></div>`).join(''); el.querySelectorAll('.open-memory').forEach(btn=>btn.onclick=()=>{ const m=memories[btn.dataset.index]; $('clientName').value=m.clientName; $('industry').value=m.industry; $('scale').value=m.scale; $('painPoints').value=m.painPoints; showView('workspace'); renderProposal(m); $('resultEmpty').classList.add('hidden'); $('proposalResult').classList.remove('hidden'); $('resultLoading').classList.add('hidden'); $('crumbTitle').textContent=m.clientName; }); }
function renderPrompts(){ $('promptGrid').innerHTML=promptState.map(p=>`<article class="prompt-card"><header><b>${p.id}</b><strong>${p.title}</strong></header><textarea data-prompt="${p.id}">${p.text}</textarea><button class="save-prompt" data-save="${p.id}">保存修改</button></article>`).join(''); $('promptGrid').querySelectorAll('.save-prompt').forEach(btn=>btn.onclick=()=>{ const id=btn.dataset.save; const area=$(`promptGrid`).querySelector(`textarea[data-prompt="${id}"]`); promptState.find(p=>p.id===id).text=area.value; localStorage.setItem('feishu_prompts',JSON.stringify(promptState)); toast('Prompt 已保存'); }); }
function renderProducts(){ $('productGrid').innerHTML=products.map(p=>`<article class="library-card"><div class="lib-icon">${p[2]}</div><h3>飞书${p[0]}</h3><p>${p[1]}</p></article>`).join(''); }
function showView(view){ document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden')); $(`${view}View`).classList.remove('hidden'); document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); if(view==='history')renderHistory(); if(view==='prompts')renderPrompts(); if(view==='products')renderProducts(); }

document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>showView(btn.dataset.view));
$('newProposalBtn').onclick=()=>{showView('workspace'); $('resultEmpty').classList.remove('hidden'); $('proposalResult').classList.add('hidden'); $('resultLoading').classList.add('hidden'); $('crumbTitle').textContent='新建提案';};
document.querySelectorAll('.tag').forEach(btn=>btn.onclick=()=>{$('painPoints').value=btn.dataset.pain;});
$('clientForm').onsubmit=(e)=>{e.preventDefault(); const data={clientName:$('clientName').value.trim(),industry:$('industry').value,scale:$('scale').value.trim(),painPoints:$('painPoints').value.trim(),savedAt:formatDate(),version:1}; if(!data.clientName||!data.scale||!data.painPoints)return toast('请补全客户画像'); runGeneration(data);};
$('clearHistoryBtn').onclick=()=>{if(!memories.length)return; memories=[]; localStorage.removeItem('feishu_memories'); updateMemoryUI(); renderHistory(); toast('记忆已清空');};
$('resetPromptsBtn').onclick=()=>{promptState=defaultPrompts.map(p=>({...p})); localStorage.removeItem('feishu_prompts'); renderPrompts(); toast('Prompt 已恢复默认');};
updateMemoryUI(); renderProducts();
